version: "3"
services:
  api:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - ./community-poll:/var/www/html
  client:
    build: .
    ports:
      - "8001:3000"
    volumes:
      - ./client-server:/var/www/html
    depends_on:
      - api